-- MySQL Script generated by MySQL Workbench
-- Sun Nov  3 20:17:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `description` VARCHAR(8000) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL,
  `update_date` TIMESTAMP NOT NULL,
  `rome_code` VARCHAR(5) NOT NULL,
  `contract_type` VARCHAR(45) NOT NULL,
  `contract_label` VARCHAR(45) NOT NULL,
  `contract_nature` VARCHAR(45) NOT NULL,
  `experience_required` CHAR NOT NULL,
  `experience_label` INT NULL,
  `work_duration` INT NULL,
  `work_duration_converted` VARCHAR(45) NULL,
  `work_conditions` VARCHAR(50) NOT NULL,
  `is_alternance` TINYINT NULL,
  `is_disabled_friendly` TINYINT NULL,
  `naf_code` VARCHAR(10) NULL,
  `qualification_code` TINYINT NULL,
  `candidates_missing` TINYINT NOT NULL,
  `activity_sector_code` TINYINT NULL,
  `moving_code` TINYINT NULL,
  `experience_requirement` VARCHAR(45) NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`salary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `salary_id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT NOT NULL,
  `min_monthly_salary` FLOAT NULL,
  `max_monthly_salary` FLOAT NULL,
  `salary_description` VARCHAR(100) NULL,
  PRIMARY KEY (`salary_id`, `job_id`),
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `salary_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`benefits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`benefits` ;

CREATE TABLE IF NOT EXISTS `mydb`.`benefits` (
  `benefits_id` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`benefits_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary_benefits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`salary_benefits` ;

CREATE TABLE IF NOT EXISTS `mydb`.`salary_benefits` (
  `salary_benefits_id` INT NOT NULL,
  `salary_id` INT NOT NULL,
  PRIMARY KEY (`salary_benefits_id`, `salary_id`),
  INDEX `salary_id_idx` (`salary_id` ASC) VISIBLE,
  CONSTRAINT `salary_benefits_benefits_id_fk`
    FOREIGN KEY (`salary_benefits_id`)
    REFERENCES `mydb`.`benefits` (`benefits_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `salary_benefits_salary_id_fk`
    FOREIGN KEY (`salary_id`)
    REFERENCES `mydb`.`salary` (`salary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL AUTO_INCREMENT,
  `insee_code` INT NOT NULL,
  `job_id` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`),
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  UNIQUE INDEX `insee_code_UNIQUE` (`insee_code` ASC) VISIBLE,
  CONSTRAINT `location_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cities` (
  `insee_code` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`insee_code`),
  CONSTRAINT `cities_insee_code`
    FOREIGN KEY (`insee_code`)
    REFERENCES `mydb`.`location` (`insee_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `is_adapted` TINYINT NULL,
  PRIMARY KEY (`company_id`),
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `companies_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`competencies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`competencies` (
  `competency_id` INT NOT NULL AUTO_INCREMENT,
  `competency_code` VARCHAR(6) NULL,
  PRIMARY KEY (`competency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_competency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_competency` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_competency` (
  `competency_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  `required` CHAR NULL,
  PRIMARY KEY (`competency_id`, `job_id`),
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `job_competency_competency_id`
    FOREIGN KEY (`competency_id`)
    REFERENCES `mydb`.`competencies` (`competency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_competency_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  `job_id` INT NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `contact_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`profesionnal_qualities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profesionnal_qualities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profesionnal_qualities` (
  `profesional_qualitiy_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`profesional_qualitiy_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_prefesional_qualities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_prefesional_qualities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_prefesional_qualities` (
  `profesional_qualitiy_id` INT NOT NULL,
  `job_id` INT NOT NULL,
  PRIMARY KEY (`profesional_qualitiy_id`, `job_id`),
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  CONSTRAINT `job_profesionnal_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `professional_quality_id_fk`
    FOREIGN KEY (`profesional_qualitiy_id`)
    REFERENCES `mydb`.`profesionnal_qualities` (`profesional_qualitiy_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`driver_license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`driver_license` ;

CREATE TABLE IF NOT EXISTS `mydb`.`driver_license` (
  `driver_license_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL,
  PRIMARY KEY (`driver_license_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_driver_license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_driver_license` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_driver_license` (
  `job_id` INT NOT NULL,
  `driver_license_id` INT NOT NULL,
  `requirement` CHAR NULL,
  PRIMARY KEY (`job_id`, `driver_license_id`),
  INDEX `driver_license_id_idx` (`driver_license_id` ASC) VISIBLE,
  CONSTRAINT `job_driver_license_job_id`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_driver_license_driver_license_id`
    FOREIGN KEY (`driver_license_id`)
    REFERENCES `mydb`.`driver_license` (`driver_license_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`formation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`formation` (
  `formation_id` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`formation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_formation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_formation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_formation` (
  `job_id` INT NOT NULL,
  `formation_id` INT NOT NULL,
  `requirement` CHAR NULL,
  PRIMARY KEY (`job_id`, `formation_id`),
  INDEX `formation_id_idx` (`formation_id` ASC) VISIBLE,
  CONSTRAINT `job_formation_job_id`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_formation_formation_id`
    FOREIGN KEY (`formation_id`)
    REFERENCES `mydb`.`formation` (`formation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job_node` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job_node` (
  `rome_code` VARCHAR(5) NOT NULL,
  `naf_code` VARCHAR(10) NOT NULL,
  `activity_sector_code` INT NOT NULL,
  `job_id` INT NOT NULL,
  INDEX `job_id_idx` (`job_id` ASC) VISIBLE,
  UNIQUE INDEX `rome_code_UNIQUE` (`rome_code` ASC) VISIBLE,
  UNIQUE INDEX `naf_code_UNIQUE` (`naf_code` ASC) VISIBLE,
  UNIQUE INDEX `activity_sector_code_UNIQUE` (`activity_sector_code` ASC) VISIBLE,
  CONSTRAINT `job_node_job_id_fk`
    FOREIGN KEY (`job_id`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rome` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rome` (
  `rome_code` VARCHAR(5) NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`rome_code`),
  CONSTRAINT `rome_code_fk`
    FOREIGN KEY (`rome_code`)
    REFERENCES `mydb`.`job_node` (`rome_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`moving`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`moving` ;

CREATE TABLE IF NOT EXISTS `mydb`.`moving` (
  `moving_code` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  PRIMARY KEY (`moving_code`),
  CONSTRAINT `moving_code`
    FOREIGN KEY (`moving_code`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`qualification` ;

CREATE TABLE IF NOT EXISTS `mydb`.`qualification` (
  `qualification_code` INT NOT NULL,
  `label` VARCHAR(100) NULL,
  PRIMARY KEY (`qualification_code`),
  CONSTRAINT `qualification_code_fk`
    FOREIGN KEY (`qualification_code`)
    REFERENCES `mydb`.`job` (`job_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`naf`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`naf` ;

CREATE TABLE IF NOT EXISTS `mydb`.`naf` (
  `naf_code` VARCHAR(10) NOT NULL,
  `label` VARCHAR(100) NULL,
  PRIMARY KEY (`naf_code`),
  CONSTRAINT `naf_code_fk`
    FOREIGN KEY (`naf_code`)
    REFERENCES `mydb`.`job_node` (`naf_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activity_sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activity_sector` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activity_sector` (
  `activity_sector_code` INT NOT NULL,
  `label` VARCHAR(100) NULL,
  PRIMARY KEY (`activity_sector_code`),
  CONSTRAINT `activity_sector_code_fk`
    FOREIGN KEY (`activity_sector_code`)
    REFERENCES `mydb`.`job_node` (`activity_sector_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`location_AFTER_INSERT` $$
USE `mydb`$$
$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
