-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 17:52:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

drop schema `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`job` ;

CREATE TABLE IF NOT EXISTS `mydb`.`job` (
  `job_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `description` VARCHAR(8000) NOT NULL,
  `creation_date` TIMESTAMP NOT NULL,
  `update_date` TIMESTAMP NOT NULL,
  `rome_code` VARCHAR(5) NOT NULL,
  `contract_type` VARCHAR(45) NOT NULL,
  `contract_label` VARCHAR(45) NOT NULL,
  `contract_nature` VARCHAR(45) NOT NULL,
  `experience_required` CHAR NOT NULL,
  `experience_label` INT NULL,
  `work_duration` INT NULL,
  `work_duration_converted` VARCHAR(45) NULL,
  `work_conditions` VARCHAR(50) NOT NULL,
  `is_alternance` TINYINT NULL,
  `is_disabled_friendly` TINYINT NULL,
  `naf_code` VARCHAR(10) NULL,
  `qualification_code` TINYINT NULL,
  `candidates_missing` TINYINT NOT NULL,
  `activity_sector_code` TINYINT NULL,
  `moving_code` TINYINT NULL,
  `experience_requirement` VARCHAR(45) NULL,
  `competency_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `salary_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`job_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`salary` ;

CREATE TABLE IF NOT EXISTS `mydb`.`salary` (
  `salary_id` INT NOT NULL AUTO_INCREMENT,
  `min_monthly_salary` FLOAT NULL,
  `max_monthly_salary` FLOAT NULL,
  `salary_description` VARCHAR(100) NULL,
  PRIMARY KEY (`salary_id`))
ENGINE = InnoDB
COMMENT = '	';

-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `location_id` INT NOT NULL auto_increment,
  `insee_code` INT NOT NULL,
  `label` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  PRIMARY KEY (`location_id`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`companies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `is_adapted` TINYINT NULL,
  PRIMARY KEY (`company_id`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`competencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`competencies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`competencies` (
  `competency_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(300) NULL,
  PRIMARY KEY (`competency_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contact` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`contact_id`)
  )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`profesionnal_qualities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profesionnal_qualities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profesionnal_qualities` (
  `profesional_qualitiy_id` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`profesional_qualitiy_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Adding foreign key to job table
-- -----------------------------------------------------
ALTER table `mydb`.`job` add constraint  foreign key (`company_id`) references `companies`(`company_id`) on delete cascade on update restrict; 

ALTER table `mydb`.`job` add constraint foreign key (`salary_id`) references `salary`(`salary_id`); 

ALTER table `mydb`.`job` add constraint foreign key (`location_id`) references `location`(`location_id`);

ALTER table `mydb`.`job` add constraint foreign key (`competency_id`) references `competencies`(`competency_id`);

ALTER table `mydb`.`job` add constraint foreign key (`contact_id`) references `contact`(`contact_id`);

 


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



DROP TABLE IF EXISTS lieuTravail;
CREATE TABLE IF NOT EXISTS lieuTravail(
commune INT  ,
codePostal FLOAT  ,
longitude FLOAT  ,
latitude FLOAT  ,
libelle VARCHAR(100)  ,
lieuTravail_id VARCHAR(100) NOT NULL ,
PRIMARY KEY ( lieuTravail_id )
);

SHOW TABLES;

select *
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='entreprise';
